# Run all tests for commits to master

name: AWK / main

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install software
        run: sudo apt update && sudo apt -y install gawk bats

      - name: Run tests for all exercises
        run: bash bin/ci
