# Run all tests for commits to master

name: AWK / main

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install software
        run: sudo apt update && sudo apt -y install gawk bats
        # bats v1.10.0 -- https://launchpad.net/ubuntu/noble/+source/bats
        # gawk v5.2.1  -- https://launchpad.net/ubuntu/noble/+source/gawk

      - name: Run tests for all exercises
        run: bash bin/ci
